import { useState } from 'react'
import Head from "next/head";
import Progress from '../components/Progress';
import axios from 'axios';


function App() {

  const [disabled, setDisabled] = useState(false);
  const [progressItems, setProgressItems] = useState([]);

  const [input, setInput] = useState(``);
  const [output, setOutput] = useState('');


  const getCounselling = async () => {
    if (!input) return
    setDisabled(true);
    const response = await axios.post('/api/get-counselling', { prompt: input });
    setOutput(response.data?.result)
    setDisabled(false);
  }

  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
      </Head>
      <main>
        <h1>User friendly Counselling :)</h1>
        <h2>We are here to help you!</h2>

        <div className='container'>
          <div className='textbox-container'>
            <textarea placeholder='Enter your problem' value={input} rows={10} onChange={e => setInput(e.target.value)}></textarea>
            <textarea value={output} rows={3} readOnly></textarea>
          </div>
        </div>

        <button disabled={disabled || !input} onClick={getCounselling}>{!disabled ? <>Get Counselling for your patient</> : <>Loading...</>}
        </button>
      </main>
    </>
  )
}

export default App
